version: '3.8'  # ระบุเวอร์ชัน

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    image: postgres:15  # ระบุเวอร์ชันชัดเจน
    environment:
      POSTGRES_USER: healthapp_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: healthapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    # เพิ่ม healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthapp_user -d healthapp_db"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  postgres_data: