export const FEATURES = [
  {
    id: 4,
    key: 'sleep',
    label: 'การนอน',
    image: require('../assets/featureIcons/sleep.png'),
    route: 'Sleep',
    // position: { top: -12, left: '50%', marginLeft: -22 },
  },
  {
    id: 5,
    key: 'exercise',
    label: 'ออกกำลังกาย',
    image: require('../assets/featureIcons/step.png'),
    route: 'Exercise',
    // position: { right: -12, top: '50%', marginTop: -22 },
  },
  {
    id: 3,
    key: 'mood',
    label: 'อารมณ์',
    image: require('../assets/featureIcons/mood.png'),
    // position: { bottom: -12, left: '50%', marginLeft: -22 },
  },
  {
    id: 2,
    key: 'calorie',
    label: 'แคลอรี่',
    image: require('../assets/featureIcons/ffood.png'),
    route: 'Calorie',
    // position: { left: -12, top: '50%', marginTop: -22 },
  },
  {
    id: 1,
    key: 'water',
    label: 'น้ำ',
    image: require('../assets/featureIcons/water.png'),
    route: 'Water',
    // position: { bottom: 24, left: 24 },
  },
];
