/** Server-side mission catalog — ids align with MyApp/src/constants/missions.js */

export const XP_BASE = {
  daily: 30,
  weekly: 80,
  monthly: 150,
};

export const MISSION_CATALOG = {
  daily: [
    {
      id: "d1",
      title: "ดื่มน้ำแก้วแรกหลังตื่นนอน",
      reward: 5,
      goal: 1,
      unit: "ครั้ง",
      metric: "water_logs_today",
    },
    {
      id: "d2",
      title: "บันทึกอาหารครบ 3 มื้อ",
      reward: 10,
      goal: 3,
      unit: "มื้อ",
      metric: "food_logs_today",
    },
    {
      id: "d3",
      title: "เดินครบ 5,000 ก้าว",
      reward: 10,
      goal: 5000,
      unit: "ก้าว",
      metric: "steps_today",
    },
    {
      id: "d4",
      title: "บันทึกอารมณ์ก่อนหมดวัน",
      reward: 10,
      goal: 1,
      unit: "ครั้ง",
      metric: "mood_logged_today",
    },
  ],
  weekly: [
    {
      id: "w1",
      title: "นอนครบ 7 ชม. อย่างน้อย 4 วัน/สัปดาห์",
      reward: 80,
      goal: 4,
      unit: "วัน",
      metric: "sleep_7h_days_week",
    },
    {
      id: "w2",
      title: "เสาร์-อาทิตย์ เดินรวมกัน 15,000 ก้าว",
      reward: 80,
      goal: 15000,
      unit: "ก้าว",
      metric: "weekend_steps_week",
    },
    {
      id: "w3",
      title: "บันทึก Calorie ต่อเนื่อง 5 วัน",
      reward: 80,
      goal: 5,
      unit: "วัน",
      metric: "food_distinct_days_week",
    },
    {
      id: "w4",
      title: "ดื่มน้ำครบตามเป้าหมาย 7 วันติดกัน",
      reward: 100,
      goal: 7,
      unit: "วัน",
      metric: "water_goal_streak",
    },
    {
      id: "w5",
      title: "สะสมก้าวย่างรวมครบ 35,000 ก้าว/สัปดาห์",
      reward: 100,
      goal: 35000,
      unit: "ก้าว",
      metric: "steps_sum_week",
    },
  ],
  monthly: [
    {
      id: "m1",
      title: "สะสมก้าวเดินครบ 50,000 ก้าว",
      reward: 150,
      goal: 50000,
      unit: "ก้าว",
      metric: "steps_sum_month",
    },
    {
      id: "m2",
      title: "มีวันที่มีความสุข (Happy Mood) > 15 วัน",
      reward: 400,
      goal: 15,
      unit: "วัน",
      metric: "happy_mood_days_month",
    },
    {
      id: "m3",
      title: "นอนหลับครบ 7-8 ชม. อย่างน้อย 20 วัน",
      reward: 500,
      goal: 20,
      unit: "วัน",
      metric: "sleep_7_8_days_month",
    },
    {
      id: "m4",
      title: "บันทึกอารมณ์ต่อเนื่องครบ 30 วัน",
      reward: 500,
      goal: 30,
      unit: "วัน",
      metric: "mood_days_month",
    },
    {
      id: "m5",
      title: "บันทึก Calorie Diary รวม 20 วัน",
      reward: 500,
      goal: 20,
      unit: "วัน",
      metric: "food_distinct_days_month",
    },
  ],
};
