/** Server-side mission catalog — ids align with MyApp/src/constants/missions.js */

export const XP_BASE = {
  daily: 30,
  weekly: 80,
  monthly: 150,
};

export const MISSION_CATALOG = {
  daily: [
    {
      id: "d1",
      title: "ดื่มน้ำอย่างน้อย 1 ครั้ง",
      reward: 5,
      goal: 1,
      unit: "ครั้ง",
      metric: "water_logs_today",
    },
    {
      id: "d2",
      title: "บันทึกอาหารอย่างน้อย 3 ครั้ง",
      reward: 10,
      goal: 3,
      unit: "ครั้ง",
      metric: "food_logs_today",
    },
    {
      id: "d3",
      title: "ออกกำลังกาย อย่างน้อย 1 วัน",
      reward: 10,
      goal: 1,
      unit: "วัน",
      metric: "exercise_session_days_today",
    },
    {
      id: "d4",
      title: "บันทึกอารมณ์ก่อนหมดวัน",
      reward: 10,
      goal: 1,
      unit: "ครั้ง",
      metric: "mood_logged_today",
    },
  ],
  weekly: [
    {
      id: "w1",
      title: "นอนครบ 7 ชม. อย่างน้อย 4 วัน",
      reward: 80,
      goal: 4,
      unit: "วัน",
      metric: "sleep_7h_days_week",
    },
    {
      id: "w2",
      title: "ออกกำลังกาย อย่างน้อย 3 วัน",
      reward: 80,
      goal: 3,
      unit: "วัน",
      metric: "exercise_distinct_days_week",
    },
    {
      id: "w3",
      title: "บันทึกอาหารต่อเนื่อง 5 วัน",
      reward: 80,
      goal: 5,
      unit: "วัน",
      metric: "food_distinct_days_week",
    },
    {
      id: "w4",
      title: "ดื่มน้ำครบตามเป้าหมาย 7 วันติดกัน",
      reward: 100,
      goal: 7,
      unit: "วัน",
      metric: "water_goal_streak",
    },
    {
      id: "w5",
      title: "ออกกำลังกาย อย่างน้อย 5 วัน",
      reward: 100,
      goal: 5,
      unit: "วัน",
      metric: "exercise_distinct_days_week",
    },
  ],
  monthly: [
    {
      id: "m1",
      title: "ออกกำลังกาย อย่างน้อย 12 วัน",
      reward: 150,
      goal: 12,
      unit: "วัน",
      metric: "exercise_distinct_days_month",
    },
    {
      id: "m2",
      title: "มีวันที่มีความสุข > 15 วัน",
      reward: 400,
      goal: 15,
      unit: "วัน",
      metric: "happy_mood_days_month",
    },
    {
      id: "m3",
      title: "นอนหลับครบ 7-8 ชม. อย่างน้อย 20 วัน",
      reward: 500,
      goal: 20,
      unit: "วัน",
      metric: "sleep_7_8_days_month",
    },
    {
      id: "m4",
      title: "บันทึกอารมณ์ต่อเนื่องครบ 30 วัน",
      reward: 500,
      goal: 30,
      unit: "วัน",
      metric: "mood_days_month",
    },
    {
      id: "m5",
      title: "บันทึกอาหาร รวม 20 วัน",
      reward: 500,
      goal: 20,
      unit: "วัน",
      metric: "food_distinct_days_month",
    },
  ],
};
